# Generated by Django 2.2.4 on 2021-06-03 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whole', '0004_auto_20210603_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='reglog.User'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='reglog.User'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.TextField(blank=True),
        ),
    ]
